INSERT INTO theme (`th_id`, `th_name`) VALUES
(1, 'Spectacle'),
(2, 'Concert'),
(3, 'Exposition'),
(4, 'Festival'),
(5, 'Evènement sportif');

INSERT INTO locations (lo_id, lo_name, lo_address, lo_city, lo_gps_lat, lo_gps_long) VALUES
(1, 'Le Corum', 'Place Charles de Gaulle, 34000 Montpellier', 'Montpellier', 43.6200000000, 3.8300000000),
(2, 'Zénith Sud', '2733 Avenue Albert Einstein, 34000 Montpellier', 'Montpellier', 43.6137900000, 3.9300100000);

INSERT INTO events (ev_id,ev_name, ev_price, ev_date_start, ev_date_end, ev_start_time, ev_end_time, ev_nb_people_min, ev_nb_people_max, ev_descriptive, ev_average, ev_lo_id, ev_th_id, ev_picture) VALUES
(1,'LE LAC DES CYGNES', 39.00, '2020-01-11', '2020-01-11', '20:30:00', '22:30:00', NULL, 500, '<p>\r\nLE LAC DES CYGNES <br>\r\nBallet classique en deux actes et 4 tableaux <br>\r\nMusique :Piotr Tchaïkovski <br>\r\nChorégraphie : Marius Petipa <br>\r\nLe Lac des cygnes a été présenté la première fois à Moscou en 1877. <br>\r\nL’histoire d’amour du prince pour une jeune fille, transformée en cygne par un sorcier, est un sujet fantastique où la danseuse principale a un double personnage à jouer et à danser – Odette, cygne blanc, lyrique et poétique, Odile, cygne noir, maléfique et fatal. <br>\r\nC’est l’école russe de danse classique, l’école d’excellence de Saint-Pétersbourg, que les spectateurs pourront voir sur scène. Les danseurs ont été formés dans les meilleures écoles de ballet de Russie d’après la méthode Vaganova de Saint-Pétersbourg. <br>\r\nLe Lac des cygnes fait partie des ballets les plus connus au monde et le plus joué dans les théâtres. <br>\r\nLa musique de Piotr Tchaïkovski transporte le spectateur dans un univers poétique, un univers de grâce, d’élégance et de beauté infinie. <br>\r\nLa splendeur des décors et des costumes, l’orchestre live, l’esthétique et la poésie de la danse classique ,interprétée avec brio et élégance par les danseurs russes, font de ce spectacle un vrai joyau pour toute la famille ! <br>Réservations Personne à Mobilité Réduite (PMR) Tél : 0467546123</p>', NULL, 1, 1, 'http://www.montpellier-events.com/var/mtp/storage/images/agenda/le-lac-des-cygnes7/60491-1-fre-FR/LE'),
(2,'Casse-Noisette', 39.00, '2020-01-19', '2020-01-19', '18:00:00', '20:00:00', NULL, 500, '				\r\n                \r\n<p><b>Casse-Noisette – </b><b>Opéra national de Russie</b></p><p><b>Vivez la magie de Noël en 2019 avec le chef d’œuvre classique <i>Casse-Noisette</i>&nbsp;!</b></p><p>Ce conte de Noël raconte l’histoire de la jeune Clara qui reçoit en cadeau un casse-noisette en forme de petit bonhomme. Dans une nuit animée d’un mystérieux enchantement, les jouets menés par Casse-Noisette se livrent à une bataille acharnée contre les méchantes souris de la maison. Réveillée par le bruit, Clara décide d’affronter ses peurs en participant au combat et sauve son cher Casse Noisette du danger. Ému par son courage et plein de gratitude, il se transforme en prince charmant et emmène Clara dans un royaume féérique.</p><p>Ballet en deux actes, Casse-Noisette&nbsp;est présenté au public pour la première fois en décembre 1892 à Saint-Pétersbourg au Théâtre Mariinsky. La célèbre musique de Tchaïkovsky interprétée par le talentueux orchestre et la virtuosité des danseurs, sublimés par des décors et costumes époustouflants, feront vibrer petits et grands dans ce monde fantastique. Cette partition inoubliable vous plongera dans une atmosphère magique et vous fera revivre vos rêves d’enfants.</p><p>Retrouvez toute la beauté de ce joyau du répertoire classique, idéal en cette période de Noël.</p><p class=\" text-justify\"><b>Réservations pour les Personnes à Mobilité Réduite : 01 55 12 00 00</b></p>            ', NULL, 1, 1, 'http://www.montpellier-events.com/var/mtp/storage/images/agenda/casse-noisette2/60511-1-fre-FR/CASSE-NOISETTE_listing_agenda2.jpg');
